# Generated by Django 3.2 on 2022-01-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220118_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_crate',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
