# Generated by Django 3.2 on 2022-01-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='year',
            field=models.CharField(blank=True, default='unkown', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='artist_name',
            field=models.CharField(blank=True, default='unkown', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, default='unkown', max_length=254),
        ),
    ]
