# Generated by Django 3.2 on 2022-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist_name',
            field=models.CharField(default='Unkown', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unkown', max_length=254),
        ),
    ]
